language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

install: travis_retry composer install --prefer-dist --no-interaction --no-suggest -v

script: vendor/bin/phpunit --debug -c phpunit.xml --coverage-clover=coverage.clover
